# Generated by Django 5.1.2 on 2024-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_remove_producto_es_promocion_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_promocion',
            field=models.BooleanField(default=False),
        ),
    ]
