# Generated by Django 5.1.2 on 2024-10-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_producto_es_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
    ]
