# Generated by Django 5.1.2 on 2024-10-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_categoria_producto_categoria'),
        ('ventas', '0008_add_default_categories'),
    ]

    operations = [
    ]
