# Generated by Django 5.1.2 on 2024-10-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_merge_20241026_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
    ]
