# Generated by Django 5.1.2 on 2024-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_rename_fecha_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero_pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
