# Generated by Django 5.1.2 on 2024-10-26 09:23

import uuid
from django.db import migrations, models


def generar_numero_pedido(apps, schema_editor):
    Pedido = apps.get_model('ventas', 'Pedido')
    for pedido in Pedido.objects.all():
        pedido.numero_pedido = uuid.uuid4().hex[:10]
        pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_rename_fecha_creacion_pedido_fecha_and_more'),  # Asegúrate de que este sea el número correcto
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        migrations.RunPython(generar_numero_pedido),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True, editable=False),
        ),
    ]
